// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-ui/ContributionRow320.tsx": () => import("../components/mockups/admin-ui/ContributionRow320.tsx"),
  "./components/mockups/admin-ui/DirA.tsx": () => import("../components/mockups/admin-ui/DirA.tsx"),
  "./components/mockups/admin-ui/DirB.tsx": () => import("../components/mockups/admin-ui/DirB.tsx"),
  "./components/mockups/admin-ui/DirC.tsx": () => import("../components/mockups/admin-ui/DirC.tsx")
};
